version: 1
additional_information:
  - code: poisluettavaKayttotarkoitus
    data_type: Code
    code_list: http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji
  - code: kerroksetJotaMaaraysKoskee
    data_type: NumericRange
  - code: kayttotarkoituskohdistus
    data_type: Code
    code_list: http://uri.suomi.fi/codelist/rytj/RY_Kaavamaarayslaji
  - code: kayttotarkoituksenOsuusKerrosalastaK-m2
    data_type: PositiveNumeric
    unit: k-m2
  - code: kayttotarkoituksenOsuusKerrosalastaPros
    data_type: PositiveNumeric
    unit: "%"
  - code: kayttotarkoituksenOsuusRakennustilavuudestaK-m3
    data_type: PositiveNumeric
    unit: m3
  - code: kayttotarkoituksenOsuusRakennustilavuudestaPros
    data_type: PositiveNumeric
    unit: "%"
  - code: kayttotarkoituksenOsuusMaapintaAlasta
    data_type: PositiveNumeric
    unit: "%"
  - code: rakennusluvanPeruste
    data_type: Code
    code_list: http://uri.suomi.fi/codelist/rytj/oikeusvaik_YK
  - code: autopaikkojenSijoittuminenSallittu
    data_type: PositiveNumeric
